### ISSUE TITLE
Migration timing in containers can cause errors

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#940]
When running `docker-compose up` the celery container will be ready before the web container.

However, migrations are run by the web container:

```
  web:
    stdin_open: true
    tty: true   # Enabled together with stdin_open so it won't raise an error when we are in pdb mode. Attach using `docker attach $(docker-compose ps -q web)`
    environment:
      POSTGRES_HOST: db  # takes precendent over .env file
      REDIS_HOST: redis  # takes precendent over .env file
    command: bash -c "cd /app/src/ &&
                      python manage.py migrate_schemas --shared &&
                      python manage.py migrate_schemas --executor=multiprocessing &&
                      python manage.py runserver 0.0.0.0:8000"   # no need for uwsgi in development, this is easier
```
which means celery might be trying to access columns or tables that don't exist yet. For example:
```
celery container started before the web container when running docker-compose up but the migrations are only run in the web container
```
Probably same thing with the celery-beat container.

What's the solution?
